//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.23 at 08:33:48 PM BST 
//


package matthew.jaxb.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the matthew.jaxb.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Entities_QNAME = new QName("", "entities");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: matthew.jaxb.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntitiesType }
     * 
     */
    public EntitiesType createEntitiesType() {
        return new EntitiesType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntitiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "entities")
    public JAXBElement<EntitiesType> createEntities(EntitiesType value) {
        return new JAXBElement<EntitiesType>(_Entities_QNAME, EntitiesType.class, null, value);
    }

}
