package matthew.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import matthew.jaxb.types.EntitiesType;
import matthew.jaxb.types.EntityType;
import matthew.jaxb.types.PropertyType;
import org.apache.commons.lang.StringUtils;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class PropertyOverview
{
	private JPanel propertyViewPanel;
	private JCheckBox idCheckboxCheckBox;
	private JTextField nameTextField;
	private JTextField typeTextField;
	private JCheckBox nullableCheckBoxCheckBox;
	private JCheckBox serialiseCheckBoxCheckBox;
	private JCheckBox textAreaCheckBoxCheckBox;
	private JTextField incomingTextField;
	private JTextField mappingTextField;
	private JButton cancelButton;
	private JButton saveButton;
	private JTextArea incomingHintTextArea;
	private JTextArea mappingHintTextArea;
	private JTextArea textAreaHintTextArea;
	private JTextArea serialiseHintTextArea;
	private JTextArea nullableHintTextArea;
	private JTextArea typeHintTextArea;
	private JTextArea nameHintTextArea;
	private JTextArea idHintTextArea;


	private final JFrame frame;
	private final EntitiesType entities;
	private final EntityType entity;
	private final boolean entityHasId;


	public PropertyOverview(final JFrame frame, final EntitiesType entities, final EntityType entity, final boolean entityHasId)
	{
		this.frame = frame;
		this.entities = entities;
		this.entity = entity;
		this.entityHasId = entityHasId;


		cancelButton.addMouseListener(new MouseAdapter()
		{
			@Override
			public void mouseClicked(MouseEvent e)
			{
				super.mouseClicked(e);

				new EntityOverview(frame, entities, entity).loadPanel();
			}
		});


		saveButton.addMouseListener(new MouseAdapter()
		{
			@Override
			public void mouseClicked(MouseEvent e)
			{
				super.mouseClicked(e);

				if (createNewProperty())
				{
					new EntityOverview(frame, entities, entity).loadPanel();
				}
			}
		});
	}

	public void loadPanel()
	{
		frame.setContentPane(propertyViewPanel);
		frame.revalidate();

		if (entityHasId)
		{
			idCheckboxCheckBox.setEnabled(false);
		}

	}

	private boolean createNewProperty()
	{
		final PropertyType property = new PropertyType();

		boolean error = false;

		final String propertyName = nameTextField.getText().replace(" ", "");
		if (StringUtils.isEmpty(propertyName))
		{
			error = true;
			// TODO show popup on panel
			System.out.println("Warning property name is required!");
		}
		if (!StringUtils.isAlphanumeric(propertyName))
		{
			error = true;
			// TODO show popup on panel
			System.out.println("Warning property name is not fully alphanumeric!");
		}
		property.setName(propertyName);

		final String propertyType = typeTextField.getText().replace(" ", "");
		if (StringUtils.isEmpty(propertyType))
		{
			error = true;
			// TODO show popup on panel
			System.out.println("Warning property type is required!");
		}
		if (!StringUtils.isAlphanumeric(propertyType))
		{
			error = true;
			// TODO show popup on panel
			System.out.println("Warning property type is not fully alphanumeric!");
		}
		property.setType(propertyType);

		property.setId(idCheckboxCheckBox.isSelected());
		property.setSerialise(serialiseCheckBoxCheckBox.isSelected());
		property.setNullable(nullableCheckBoxCheckBox.isSelected());
		property.setTextArea(textAreaCheckBoxCheckBox.isSelected());

		final String propertyIncoming = incomingTextField.getText().replace(" ", "");
		if (!StringUtils.isAlphanumeric(propertyIncoming))
		{
			error = true;
			// TODO show popup on panel
			System.out.println("Warning property incoming is not fully alphanumeric!");
		}
		property.setIncoming(propertyIncoming);

		final String propertyMapping = mappingTextField.getText().replace(" ", "");
		if (!StringUtils.isAlphanumeric(propertyMapping))
		{
			error = true;
			// TODO show popup on panel
			System.out.println("Warning property mapping is not fully alphanumeric!");
		}
		property.setMapping(propertyMapping);

		if (!error)
		{
			entity.getProperty().add(property);
		}

		return !error;

	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		propertyViewPanel = new JPanel();
		propertyViewPanel.setLayout(new GridLayoutManager(13, 3, new Insets(5, 5, 5, 5), -1, -1));
		final JLabel label1 = new JLabel();
		label1.setText("Attributes");
		propertyViewPanel.add(label1,
		                      new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		final Spacer spacer1 = new Spacer();
		propertyViewPanel.add(spacer1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
		                                                   GridConstraints.FILL_HORIZONTAL,
		                                                   GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null,
		                                                   null, 0,
		                                                   false));
		final Spacer spacer2 = new Spacer();
		propertyViewPanel.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
		                                                   GridConstraints.FILL_VERTICAL, 1,
		                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0,
		                                                   false));
		final JLabel label2 = new JLabel();
		label2.setText("ID");
		propertyViewPanel.add(label2,
		                      new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		final Spacer spacer3 = new Spacer();
		propertyViewPanel.add(spacer3, new GridConstraints(12, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
		                                                   GridConstraints.FILL_VERTICAL, 1,
		                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0,
		                                                   false));
		idCheckboxCheckBox = new JCheckBox();
		idCheckboxCheckBox.setText("");
		propertyViewPanel.add(idCheckboxCheckBox,
		                      new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_CAN_SHRINK |
		                                          GridConstraints.SIZEPOLICY_CAN_GROW,
		                                          GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false
		                      )
		);
		final JLabel label3 = new JLabel();
		label3.setText("Name");
		propertyViewPanel.add(label3,
		                      new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		nameTextField = new JTextField();
		propertyViewPanel.add(nameTextField, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST,
		                                                         GridConstraints.FILL_HORIZONTAL,
		                                                         GridConstraints.SIZEPOLICY_WANT_GROW,
		                                                         GridConstraints.SIZEPOLICY_FIXED, null,
		                                                         new Dimension(150, -1), null, 0, false));
		final JLabel label4 = new JLabel();
		label4.setText("Type");
		propertyViewPanel.add(label4,
		                      new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		typeTextField = new JTextField();
		propertyViewPanel.add(typeTextField, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST,
		                                                         GridConstraints.FILL_HORIZONTAL,
		                                                         GridConstraints.SIZEPOLICY_WANT_GROW,
		                                                         GridConstraints.SIZEPOLICY_FIXED, null,
		                                                         new Dimension(150, -1), null, 0, false));
		final JLabel label5 = new JLabel();
		label5.setText("Nullable");
		propertyViewPanel.add(label5,
		                      new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		final JLabel label6 = new JLabel();
		label6.setText("Serialise");
		propertyViewPanel.add(label6,
		                      new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		final JLabel label7 = new JLabel();
		label7.setText("Text Area");
		propertyViewPanel.add(label7,
		                      new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		final JLabel label8 = new JLabel();
		label8.setText("Incoming");
		propertyViewPanel.add(label8,
		                      new GridConstraints(10, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		final JLabel label9 = new JLabel();
		label9.setText("Mapping");
		propertyViewPanel.add(label9,
		                      new GridConstraints(11, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		nullableCheckBoxCheckBox = new JCheckBox();
		nullableCheckBoxCheckBox.setText("");
		propertyViewPanel.add(nullableCheckBoxCheckBox,
		                      new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_CAN_SHRINK |
		                                          GridConstraints.SIZEPOLICY_CAN_GROW,
		                                          GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false
		                      )
		);
		serialiseCheckBoxCheckBox = new JCheckBox();
		serialiseCheckBoxCheckBox.setText("");
		propertyViewPanel.add(serialiseCheckBoxCheckBox,
		                      new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_CAN_SHRINK |
		                                          GridConstraints.SIZEPOLICY_CAN_GROW,
		                                          GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false
		                      )
		);
		textAreaCheckBoxCheckBox = new JCheckBox();
		textAreaCheckBoxCheckBox.setText("");
		propertyViewPanel.add(textAreaCheckBoxCheckBox,
		                      new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_CAN_SHRINK |
		                                          GridConstraints.SIZEPOLICY_CAN_GROW,
		                                          GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false
		                      )
		);
		incomingTextField = new JTextField();
		propertyViewPanel.add(incomingTextField, new GridConstraints(10, 1, 1, 1, GridConstraints.ANCHOR_WEST,
		                                                             GridConstraints.FILL_HORIZONTAL,
		                                                             GridConstraints.SIZEPOLICY_WANT_GROW,
		                                                             GridConstraints.SIZEPOLICY_FIXED, null,
		                                                             new Dimension(150, -1), null, 0, false));
		mappingTextField = new JTextField();
		propertyViewPanel.add(mappingTextField, new GridConstraints(11, 1, 1, 1, GridConstraints.ANCHOR_WEST,
		                                                            GridConstraints.FILL_HORIZONTAL,
		                                                            GridConstraints.SIZEPOLICY_WANT_GROW,
		                                                            GridConstraints.SIZEPOLICY_FIXED, null,
		                                                            new Dimension(150, -1), null, 0, false));
		cancelButton = new JButton();
		cancelButton.setText("Cancel");
		propertyViewPanel.add(cancelButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
		                                                        GridConstraints.FILL_HORIZONTAL,
		                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK |
		                                                        GridConstraints.SIZEPOLICY_CAN_GROW,
		                                                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
		                                                        false
		));
		saveButton = new JButton();
		saveButton.setText("Save");
		propertyViewPanel.add(saveButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER,
		                                                      GridConstraints.FILL_HORIZONTAL,
		                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK |
		                                                      GridConstraints.SIZEPOLICY_CAN_GROW,
		                                                      GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
		                                                      false
		));
		final Spacer spacer4 = new Spacer();
		propertyViewPanel.add(spacer4, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER,
		                                                   GridConstraints.FILL_HORIZONTAL,
		                                                   GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null,
		                                                   null, 0,
		                                                   false));
		incomingHintTextArea = new JTextArea();
		propertyViewPanel.add(incomingHintTextArea,
		                      new GridConstraints(10, 2, 1, 1, GridConstraints.ANCHOR_CENTER,
		                                          GridConstraints.FILL_BOTH,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50),
		                                          null, 0, false)
		);
		mappingHintTextArea = new JTextArea();
		propertyViewPanel.add(mappingHintTextArea,
		                      new GridConstraints(11, 2, 1, 1, GridConstraints.ANCHOR_CENTER,
		                                          GridConstraints.FILL_BOTH,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50),
		                                          null, 0, false)
		);
		textAreaHintTextArea = new JTextArea();
		propertyViewPanel.add(textAreaHintTextArea,
		                      new GridConstraints(9, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50),
		                                          null, 0, false)
		);
		serialiseHintTextArea = new JTextArea();
		propertyViewPanel.add(serialiseHintTextArea,
		                      new GridConstraints(8, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50),
		                                          null, 0, false)
		);
		nullableHintTextArea = new JTextArea();
		propertyViewPanel.add(nullableHintTextArea,
		                      new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50),
		                                          null, 0, false)
		);
		typeHintTextArea = new JTextArea();
		propertyViewPanel.add(typeHintTextArea,
		                      new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50),
		                                          null, 0, false)
		);
		nameHintTextArea = new JTextArea();
		propertyViewPanel.add(nameHintTextArea,
		                      new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50),
		                                          null, 0, false)
		);
		idHintTextArea = new JTextArea();
		propertyViewPanel.add(idHintTextArea,
		                      new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW,
		                                          GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50),
		                                          null, 0, false)
		);
		final JLabel label10 = new JLabel();
		label10.setText("Property Overview");
		propertyViewPanel.add(label10,
		                      new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
		                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
		                                          null, null, null, 0, false)
		);
		label3.setLabelFor(nameTextField);
		label4.setLabelFor(typeTextField);
		label8.setLabelFor(incomingTextField);
		label9.setLabelFor(mappingTextField);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{ return propertyViewPanel; }

	// TODO fill in hint text areas


}
